version: "3"
services:
 rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    environment:
      # time 
      - "TZ=Europe/Istanbul"
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
 